Fix stuff

diff --git a/aif b/aif
--- a/aif
+++ b/aif
@@ -1510,7 +1510,7 @@ install_base() {
 	F2FS_CHECK=$(echo "f2fs-tools" "-" off)
 	KERNEL="n"
 	kernels="linux-lts linux-grsec linux-zen"
-
+	#TODO remove grsec kernel as no more in arch-repo. Substitute with linux-hardened?
 	# User to select "standard" or "advanced" installation Method
 	dialog --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title " $_InstBseTitle " --menu "$_InstBseBody" 0 0 2 \
  	"1" "$_InstStandBase" \
@@ -1576,10 +1576,15 @@ install_base() {
 		# If at least one kernel selected, proceed with installation.
 		elif [[ $KERNEL == "y" ]]; then
 			clear
-			[[ $(cat ${ANSWER}) -eq 1 ]] && pacstrap ${MOUNTPOINT} $(pacman -Sqg base | sed 's/^linux$//') $(cat ${PACKAGES}) btrfs-progs f2fs-tools sudo 2>/tmp/.errlog
+			[[ $(cat ${ANSWER}) -eq 1 ]] && pacstrap ${MOUNTPOINT} $(pacman -Sqg base | sed 's/^linux$//') $(cat ${PACKAGES}) btrfs-progs f2fs-tools sudo 2>/tmp/.errlog 
 			[[ $(cat ${ANSWER}) -eq 2 ]] && pacstrap ${MOUNTPOINT} $(cat ${PACKAGES}) 2>/tmp/.errlog
-			check_for_error
-		
+			#This bypass a bug that cause the installer to error after failing to execute 
+			#systemd-tmpfiles.hook. Note that the installation could still be continued.
+			#This may cause in case of exit codes errors, ignore meanengful errors
+			#TODO patch the hook before executing this pacman call.
+			if [[$? -ne 0]]
+				check_for_error
+			fi
 			# If the virtual console has been set, then copy config file to installation
 			[[ -e /tmp/vconsole.conf ]] && cp -f /tmp/vconsole.conf ${MOUNTPOINT}/etc/vconsole.conf 2>/tmp/.errlog
 			# If specified, copy over the pacman.conf file to the installation
